### ISSUE TITLE
Kompatibilita SPŠEI Ostrava

### ISSUE THREAD

**Issue by TenViki** [hernikplays/canteenlib#2]
**Popište chybu**
Aplikace nefunguje pro systém iCanteen 2.17.03

**Kód + chybová hláška**
žádná - zaseklé na načítání burzy, obědů

**Očekávané chování**
Úspěšné načtení informací

**Detaily**
 - OS: Android
- URL na iCanteen instanci (nebo alespoň verzi): [iCanteen 2.17.03](https://obedy.spseiostrava.cz:8443/)

**Comment by hernikplays** [comment]
Potřebuju, abys šel na hlavní stránku jídelníčku (obvykle neco jako `"/faces/secured/main.jsp?day=`) a zkopíroval mi celý HTML kód stránky a nahrál někde na pastebin nebo něco, případně i s tou celou URL adresou pokud není stejná jako v kódu.

https://github.com/hernikplays/canteenlib/blob/main/lib/src/canteen.dart#L274

**Comment by TenViki** [comment]
https://pastebin.com/iDTPMfGb
Na adrese https://obedy.spseiostrava.cz:8443/faces/secured/main.jsp

**Comment by hernikplays** [comment]
Podívám se na to co nejdřív, díky

**Comment by hernikplays** [comment]
@TenViki teď už by to mohlo fungovat, pokud to chceš testovat skrz OpenCanteen, musíš mi na mail (mám na profilu) poslat gmail adresu, kterou můžu přidat do interního testování na Google Play, protože to nemůžu dát veřejně dokud to nebude otestované *(a pokud nemáš android tak si prostě stáhni emulátor :wink: )*

**Comment by hernikplays** [comment]
> Jasně, [REDACTED]

Měl bys teď mít v obchodu play dostupnou verzi `1.4.2` (pokud ti to nabídne aktualizaci a na stránce aplikace bude napsané `(interní)` tak to funguje, kdyžtak to možná chvíli trvá), případné nefunkčnosti mi piš sem, nejlépe i se screenshoty, díky :v:
